CREATE DATABASE SCHOOL
GO
USE SCHOOL
GO

CREATE TABLE STUDENTS(
ID INT PRIMARY KEY NOT NULL,
NAME NVARCHAR(50) NOT NULL,
LASTNAME NVARCHAR(50) NOT NULL,
CELLPHONE NVARCHAR(12) NOT NULL,
)

INSERT INTO STUDENTS VALUES('1','Millaray','Rodriguez','4561120555');
DROP TABLE STUDENTS
SELECT*FROM STUDENTS